### ISSUE TITLE
Runtime Error when using preproc.dtm

### ISSUE THREAD

**Issue by SamuelHelspr** [WZBSocialScienceCenter/tmtoolkit#24]
Hi there,
I am trying to use the preprocessing method with multi process but im getting the following error:

`INFO:tmtoolkit:init with 606 documents
INFO:tmtoolkit:init with max. 4 workers
INFO:tmtoolkit:distributing work via greedy partitioning
INFO:tmtoolkit:setting up 4 worker processes
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/samuelhelsper/Downloads/tm_corona-master/prepare.py", line 101, in <module>
    preproc = TMPreproc(corpus, language='de')
  File "/Users/samuelhelsper/Downloads/tm_corona-master/venv/lib/python3.9/site-packages/tmtoolkit/preprocess/_tmpreproc.py", line 152, in __init__
    self._setup_workers(docs=docs)
  File "/Users/samuelhelsper/Downloads/tm_corona-master/venv/lib/python3.9/site-packages/tmtoolkit/preprocess/_tmpreproc.py", line 1869, in _setup_workers
    w.start()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
INFO:tmtoolkit:sending shutdown signal to workers (force=False)`

Unfortunately, my deeper python knowledge is limited. Therefor I am unsure if this is an issue with my code or with tmtoolkit. If its the former please just ignore this issue.

Thanks a lot in advance and greetings
Samuel

**Comment by internaut** [comment]
Hi, which version of tmtoolkit are you using and which OS are you running it on?
